// AI summary card. Shimmer while loading; fallback notice on degradation.
function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

// Wrap each query term occurrence with <mark>.
function highlight(text, terms) {
  if (!text) return "";
  const toks = [...new Set((terms || []).filter((t) => t && t.length >= 3))];
  if (toks.length === 0) return text;
  const re = new RegExp(`(${toks.map(escapeRe).join("|")})`, "gi");
  return text.replace(re, "<mark>$1</mark>");
}

// Human-readable explanation for each degradation reason.
function reasonText(reason) {
  switch (reason) {
    case "rate_limited":         return "AI summary unavailable — Gemini API daily quota exhausted. Results below are unaffected.";
    case "no_key":               return "AI summary disabled — no Gemini API key configured.";
    case "skipped_navigational": return null; // intentional skip; don't render the card at all
    case "no_results":           return null;
    case "parse_failed":         return "AI returned an unparseable response. Try again.";
    case "error":                return "AI summary failed to generate. Try again later.";
    default:                     return "AI summary unavailable.";
  }
}

export default function AnswerCard({ answer, loading, queryTerms, reason }) {
  // Intentional skip cases render nothing.
  if (!loading && !answer && (reason === "skipped_navigational" || reason === "no_results")) {
    return null;
  }

  const hasAnswer = !!(answer && answer.text);
  const fallback = !loading && !hasAnswer ? reasonText(reason) : null;
  if (!loading && !hasAnswer && !fallback) return null;

  return (
    <div className="answer" role="complementary">
      <div className="answer-head">
        <span className="spark" aria-hidden>✦</span>
        <span>AI Summary</span>
        {loading && <span className="answer-status">generating…</span>}
      </div>

      {loading ? (
        <div className="answer-skel">
          <div className="line" /><div className="line" /><div className="line short" />
        </div>
      ) : hasAnswer ? (
        <>
          <p
            className="answer-text"
            dangerouslySetInnerHTML={{ __html: highlight(answer.text, queryTerms) }}
          />
          {answer.sourceSentences && answer.sourceSentences.length > 0 && (
            <div className="answer-sources">
              {answer.sourceSentences.map((s, i) => (
                <div
                  key={i}
                  className="answer-source"
                  dangerouslySetInnerHTML={{ __html: `“${highlight(s, queryTerms)}”` }}
                />
              ))}
            </div>
          )}
          <div className="answer-foot">Generated by Gemini · Verify with sources below</div>
        </>
      ) : (
        <div className="answer-fallback">{fallback}</div>
      )}
    </div>
  );
}
