-- 1. Enable the pgvector extension for AI semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create the core table for our crawled data
CREATE TABLE IF NOT EXISTS documents (
    id SERIAL PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,
    title TEXT,
    content TEXT NOT NULL,
    crawled_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- This column will hold the 384-dimensional array generated by our AI model later
    embedding vector(384) 
);

-- 3. Create an index to make exact URL lookups lightning fast (prevents duplicate crawling)
CREATE INDEX IF NOT EXISTS idx_documents_url ON documents(url);

-- Note: We will create the HNSW (Hierarchical Navigable Small World) index on the 
-- embedding column in Phase 3 once we actually have vector data.